#!/bin/sh -e
echo "postrm: $@"

case "$1" in
    remove)
    ;;

    purge)
        rm -f /etc/snapraid-runner.conf
        if which ucf >/dev/null; then
            ucf --purge /etc/snapraid-runner.conf
        fi
    ;;

    disappear|upgrade|failed-upgrade|abort-install|abort-upgrade)
    ;;

    *) echo "$0: didn't understand being called with \`$1'" 1>&2
    ;;
esac

exit 0