#!/bin/sh -e
echo "postinst: $@"

case "$1" in
    configure|reconfigure)
        touch /var/log/snapraid.log
        chmod +w /var/log/snapraid.log
        ucf /opt/snapraid-runner/configuration /etc/snapraid-runner.conf
        ucfr snapraid-runner /etc/snapraid-runner.conf
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac